[package]
name = "latte"
version = "0.1.0"
authors = ["Karol Waszczuk <waszczukarol@gmail.com>"]
edition = "2018"

[dependencies]
base = { path = "src/base" }
parser = { path = "src/parser" }
compiler = { path = "src/compiler" }

[workspace]
members = ["src/base", "src/parser", "src/compiler", "src/parser/generate"]

[[bin]]
name = "latc_x86"
path = "src/compiler/src/main.rs"

[[bin]]
name = "latc"
path = "src/cli/src/main.rs"
